# Generated by Django 4.2.11 on 2024-07-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinho',
            name='livros',
        ),
    ]
